SELECT SYSDATETIME()

DECLARE 
	@var1	DATETIME=SYSDATETIME()
	,@var2 DATETIME2=SYSDATETIME()
SELECT
	@var1 ,@var2

--DATETIME2 motsvarar SYSDATETIME
--DATETIME motsvarar GETDATE
SELECT GETDATE()
SELECT SYSDATETIME()
